export const countryData = [
    'Abkhazia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Albania',
    'Algeria',
    'Andorra',
    'Antarctica',
    'Argentina',
    'Armenia',
    'Afghanistan',
    'Bahamas',
    'Bangladesh',
    'Belarus',
    'Belgium',
    'Bermuda',
    'Bulgaria',
    'Bolivia, plurinational state of',
    'Bosnia and Herzegovina',
    'Brazil',
    'Hungary',
    'Venezuela',
    'Vietnam',
    'Haiti',
    'Guatemala',
    'Guinea',
    'Germany',
    'Hong Kong',
    'Greenland',
    'Greece',
    'Georgia',
    'Denmark',
    'Dominican Republic',
    'Egypt',
    'Zimbabwe',
    'Israel',
    'India',
    'Indonesia',
    'Jordan',
    'Iraq',
    'Iran, Islamic Republic of',
    'Ireland',
    'Iceland',
    'Spain',
    'Italy',
    'Kazakhstan',
    'Canada',
    'Kenya',
    'Cyprus',
    'Kyrgyzstan',
    'China',
    'Colombia',
    'Korea, Democratic People\'s republic of',
    'Korea, Republic of',
    'Cuba',
    'Kuwait',
    'Lao People\'s Democratic Republic',
    'Latvia',
    'Lebanon',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Mauritius',
    'Madagascar',
    'Maldives',
    'Malta',
    'Morocco',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Namibia',
    'Nepal',
    'Niger',
    'Nigeria',
    'Netherlands',
    'Nicaragua',
    'New Zealand',
    'Norway',
    'United Arab Emirates',
    'Norfolk Island',
    'Pakistan',
    'Holy See (Vatican City State)',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Macedonia, The Former Yugoslav Republic Of',
    'Russian Federation',
    'Romania',
    'San Marino',
    'Saudi Arabia',
    'Serbia',
    'Seychelles',
    'Singapore',
    'Syrian Arab Republic',
    'Slovakia',
    'Slovenia',
    'United Kingdom',
    'United States',
    'Somalia',
    'Sudan',
    'Sierra Leone',
    'Tajikistan',
    'Thailand',
    'Taiwan, Province of China',
    'Tanzania, United Republic Of',
    'Tunisia',
    'Turkmenistan',
    'Turkey',
    'Uganda',
    'Uzbekistan',
    'Ukraine',
    'Uruguay',
    'Fiji',
    'Philippines',
    'Finland',
    'Falkland Islands (Malvinas)',
    'France',
    'Croatia',
    'Central African Republic',
    'Chad',
    'Montenegro',
    'Czech Republic',
    'Chile',
    'Switzerland',
    'Sweden',
    'Sri Lanka',
    'Ecuador',
    'Estonia',
    'Ethiopia',
    'South Africa',
    'Jamaica',
    'Japan'
]